# Generated by Django 4.2.1 on 2023-05-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kompyuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('xotira', models.CharField(max_length=50)),
                ('protsessor', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
    ]
